-- MySQL Script generated by MySQL Workbench
-- Tue Aug 14 11:15:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_sys_vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sys_vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sys_vendas` DEFAULT CHARACTER SET utf8 ;
USE `db_sys_vendas` ;

-- -----------------------------------------------------
-- Table `db_sys_vendas`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabela de fornecedores';


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`clientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `sobre_nome` VARCHAR(45) NULL DEFAULT NULL,
  `nascimento` DATE NULL DEFAULT NULL,
  `pessoa` ENUM('Física', 'Jurídica') NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `situacao` VARCHAR(45) NULL DEFAULT NULL,
  `observacoes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Dados dos Clientes';


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`enderecos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `fone` VARCHAR(45) NULL DEFAULT NULL,
  `observacoes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`enderecos_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`enderecos_clientes` (
  `fk_endereco` INT(11) NULL DEFAULT NULL,
  `fk_cliente` INT(11) NULL DEFAULT NULL,
  INDEX `fk_eder_clien_cliente_idx` (`fk_cliente` ASC) VISIBLE,
  INDEX `fk_ender_client_ender_idx` (`fk_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_ender_clien_cliente`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `db_sys_vendas`.`clientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ender_client_ender`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `db_sys_vendas`.`enderecos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Relacao Endereco e Clientes';


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`estoques` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `qtd_entrada` INT(11) NULL DEFAULT '0',
  `qtd_saida` INT(11) NULL DEFAULT '0',
  `qtd_minima` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`fornecedores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `pessoa` ENUM('Física', 'Jurídica') NULL DEFAULT NULL,
  `cnpj_cpf` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `fone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `observacoes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabela de fornecedores';


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`orcamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`orcamentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_cliente` INT(11) NULL DEFAULT NULL,
  `fk_usuario` INT(11) NULL DEFAULT NULL,
  `subtotal` INT(11) NULL DEFAULT NULL,
  `descontos` INT(11) NULL DEFAULT NULL,
  `total` INT(11) NULL DEFAULT NULL,
  `data_lancamento` DATE NULL DEFAULT NULL,
  `confirmado` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_orcamento_usuarios` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_orcamento_clientes_idx` (`fk_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_orcamento_clientes`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `db_sys_vendas`.`clientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orcamento_usuarios`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `db_sys_vendas`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela de orcamentos';


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_categoria` INT(11) NULL DEFAULT NULL,
  `fk_estoque` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `indicacao` VARCHAR(45) NULL DEFAULT NULL,
  `volume` VARCHAR(45) NULL DEFAULT NULL,
  `custo_unid` INT(11) NULL DEFAULT NULL,
  `sugestao_venda` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_categorias_idx` (`fk_categoria` ASC) VISIBLE,
  INDEX `fk_produtos_estoques_idx` (`fk_estoque` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categorias`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `db_sys_vendas`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produtos_estoques`
    FOREIGN KEY (`fk_estoque`)
    REFERENCES `db_sys_vendas`.`estoques` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`orcamentos_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`orcamentos_produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_orcamento` INT(11) NULL DEFAULT NULL,
  `fk_produto` INT(11) NULL DEFAULT NULL,
  `qtd` INT(11) NULL DEFAULT NULL,
  `sub_total` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orcamentoproduto_orcamentos_idx` (`fk_orcamento` ASC) VISIBLE,
  INDEX `fk_orcamentoproduto_produtos_idx` (`fk_produto` ASC) VISIBLE,
  CONSTRAINT `fk_orcamentoproduto_orcamentos`
    FOREIGN KEY (`fk_orcamento`)
    REFERENCES `db_sys_vendas`.`orcamentos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orcamentoproduto_produtos`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `db_sys_vendas`.`produtos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabela carrinho';


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`pagamentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_orcamento` INT(11) NULL DEFAULT NULL,
  `valor_total` INT(11) NULL DEFAULT NULL,
  `qtd_parcelas` INT(11) NULL DEFAULT NULL,
  `valor_parcela` INT(11) NULL DEFAULT NULL,
  `dia_vencimento` INT(11) NULL DEFAULT NULL,
  `parcelas_pagas` INT(11) NULL DEFAULT NULL,
  `status` ENUM('ATRASADO', 'EM DIAS', 'QUITADO') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamentos_orcamentos_idx` (`fk_orcamento` ASC) VISIBLE,
  CONSTRAINT `fk_pagamentos_orcamentos`
    FOREIGN KEY (`fk_orcamento`)
    REFERENCES `db_sys_vendas`.`orcamentos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sys_vendas`.`produtos_fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sys_vendas`.`produtos_fornecedores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_produto` INT(11) NOT NULL,
  `fk_fornecedor` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtofornecedor_produto_idx` (`fk_produto` ASC) VISIBLE,
  INDEX `fk_prod_forn_fornecedorer_idx` (`fk_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_prod_forn_fornecedorer`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `db_sys_vendas`.`fornecedores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prod_forn_produtos`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `db_sys_vendas`.`produtos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Relacionamento entre produtos e fornecedores';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
